<a href="https://colab.research.google.com/github/Romane-lrnt/GitConcepts/blob/main/Cours10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a[1,5]

13

In [ ]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:, 2]

array([ 3, 10])

In [ ]:
a[-1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
a[0, 1:-1:2] #[startindex:endindex:stepsize]

array([2, 4, 6])

In [ ]:
a[1,5]=20

a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b=[[[1,2],[3,4]], [[5,6], [7,8]]]
print(b)

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


In [ ]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
arr=np.array([[1,0,1]])
r1=np.repeat(arr,3,axis=0)
print(r1)
r1[1,1]=2
print(r1)

[[1 0 1]
 [1 0 1]
 [1 0 1]]
[[1 0 1]
 [1 2 1]
 [1 0 1]]


In [ ]:
a=np.array([1,2,3,4])
print(a)
a+2

[1 2 3 4]


array([3, 4, 5, 6])

In [ ]:
f=np.random.randint(-10,10, size=(4,4))
print(f)

g=np.random.randint(-4,10, size=(3,3))
print(g)

print(np.linalg.det(f))
print(np.linalg.det(g))

[[-1 -6  7 -8]
 [-5  9 -7  4]
 [ 8 -5  5 -2]
 [-4 -5 -5 -7]]
[[-2 -2 -4]
 [-1 -4  2]
 [-1 -2 -3]]
2488.9999999999986
-13.999999999999996


In [ ]:
y=np.arange(10,31)
y[4]=1
print(y)

[10 11 12 13  1 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
